In [2]:
import glob
from scipy import ndimage
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path_img = "/home/sansii/Downloads/Compressed/MiddEval3-data-Q/MiddEval3/trainingQ/"
path_disp = "/home/sansii/Downloads/Compressed/MiddEval3-GT0-Q/MiddEval3/trainingQ/"

In [9]:
def processs_input_image(image):
    image=np.array(image,dtype=np.float32)
    image=(image-np.mean(image))/np.std(image)
    return image

def convert_pfm_png(path):
    out_disp = out = glob.glob(path_disp+"*")
    print("Converting_started")
    for ou_disp in out_disp:
        print(ou_disp)
        os.system('convert'+' '+ou_disp+"/disp0GT.pfm"+' '+ou_disp+"/disp.png")
    print("Converting_Finished")
def load_disp(path):
    return np.round(ndimage.imread(path,flatten=True)/256.0)
def load_middleburry(path, path_disp):
    out_img = glob.glob(path+"*")
    out_disp = out = glob.glob(path_disp+"*")
    left_images = []
    right_images = []
    disp_images = []
    i=0
    
    for ou_img, ou_disp in zip(out_img, out_disp):
    
        print('\r', str((i/ (len(out) -1)) * 100),end='')
        i = i+1
        L_image = processs_input_image(ndimage.imread(ou_img+"/im0.png"))
        R_image = processs_input_image(ndimage.imread(ou_img+"/im1.png"))
        disp = load_disp(ou_disp+"/disp.png")
        
        
        
#         left_images.append(L_image)
#         right_images.append(R_image)
#         disp_images.append(disp)
        
    path = "/media/sansii/Software/san_projects/Major_project/Middleburry_dataset/numpy"
    np.save(path+"/left_images.npy", left_images)
    np.save(path+"/right_images.npy", right_images)
    np.save(path+"/disp_image.npy", disp_images)



In [13]:
path = "/media/sansii/Software/san_projects/Major_project/Middleburry_dataset/numpy"
disp_images = np.load(path+"/disp_image.npy",allow_pickle=True)

In [28]:
out = ndimage.imread("/home/sansii/Downloads/Compressed/MiddEval3-GT0-Q/MiddEval3/trainingQ/ArtL/disp.png")
out = out / 255.0
print()
img = 4
%matplotlib
plt.figure(0)
plt.imshow(disp_images[img],cmap='jet')
print(disp_images[img][disp_images[img]<256].max())
plt.figure(1)
plt.imshow(out,cmap='jet')

[[ 11.  11.  11. ...  26.  26. 256.]
 [ 11.  11.  11. ...  26. 256. 256.]
 [ 11.  11.  11. ... 256. 256. 256.]
 ...
 [ 59.  59.  59. ...  59.  59.  59.]
 [ 60.  60.  60. ...  59.  59.  59.]
 [ 60.  60.  60. ...  59.  59.  59.]]
Using matplotlib backend: TkAgg
74.0


In [29]:
cols =1240
start=0
end = cols

while start<cols-1:
#     for disp in range(n_classes):
#         if (end-disp  > 0):
#             if (cols > start-disp ):

#                 left_features = h9_left[:,:,max(start,disp):min(end,cols),:]
#                 right_features = h9_right[:,:,max(0,start-disp ):min(end-disp ,cols-disp),:]

#                 multiplication = np.multiply(left_features,right_features)
#                 inner_product = np.sum(multiplication,axis=3)
#                 prod[:,:,max(start,disp):min(end,cols),disp]=inner_product

    print(start)
    start = end
    end += cols


0


In [7]:
a = np.array([1,3,4,6,6,6])
print(np.argmax(a))

3


In [29]:
print(np.random.choice([1,2,3,4], replace=False))

1


In [44]:
b= [2]
b.append(3)
print(b)
b =[1]
print(b)

[2, 3]
[1]


In [49]:
# [Graded]
def argmax(q_values):
   
    """
    Takes in a list of q_values and returns the index of the item 
    with the highest value. Breaks ties randomly.
    returns: int - the index of the highest value in q_values
    """
    top_value = float("-inf")
    ties = []
    
    for i in range(len(q_values)):
        # if a value in q_values is greater than the highest value update top and reset ties to zero   
        # if a value is equal to top value add the index to ties         
        # return a random selection from ties. (hint: look at np.random.choice)
     
        ### BEGIN SOLUTION (~5-7 lines)
            
        if  top_value < q_values[i]:
            top_value = q_values[i]
            ties = []
            
        if top_value == q_values[i]:
            ties.append(i)
            
        
            
        ### END SOLUTION
    print(ties)
    out = np.random.choice(ties)
    print(out)

    return out# change this

In [50]:
# Test argmax implentation
test_array = [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
assert argmax(test_array) == 8, "Check your argmax implementation returns the index of the largest value"

# set random seed so results are deterministic
np.random.seed(0)
test_array = [1, 0, 0, 1]

total = 0
for i in range(100):
    total += argmax(test_array)

# make sure argmax does not always choose first entry
assert total > 0, "Make sure your argmax implementation randomly choooses among the largest values."

# make sure argmax does not always choose last entry
assert total != 300, "Make sure your argmax implementation randomly choooses among the largest values."

print(total)
# make sure the random number generator is only being called once per iteration
grader.test(total, 168, "Make sure the random number generator is only being called once per iteration. Consider np.random.choice to choose between ties.")

# save the results for the autograder
grader.record("argmax_test", total)

[8]
8
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
0
[0, 3]
0
[0, 3]
3
[0, 3]
3
[0, 3]
0
168


NameError: name 'grader' is not defined